// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
// import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
 // ...
await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,
);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-n36-szZO2ZkZmu-0qzLUeY1GLScQCEM',
    appId: '1:86947622453:web:f7ef1b07ab9d3835988b7c',
    messagingSenderId: '86947622453',
    projectId: 'fmfp-fbb61',
    authDomain: 'fmfp-fbb61.firebaseapp.com',
    storageBucket: 'fmfp-fbb61.appspot.com',
    measurementId: 'G-VCWG8V1GJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNjCspnO2bgohNfjeP4JOLw1N9BiBbmi0',
    appId: '1:86947622453:android:18673f9b20d7cc35988b7c',
    messagingSenderId: '86947622453',
    projectId: 'fmfp-fbb61',
    storageBucket: 'fmfp-fbb61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLmi8_ZmVq0myTExOPc3StYd6i0QoLoNo',
    appId: '1:86947622453:ios:be86c55b62667617988b7c',
    messagingSenderId: '86947622453',
    projectId: 'fmfp-fbb61',
    storageBucket: 'fmfp-fbb61.appspot.com',
    iosBundleId: 'com.example.fmfp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLmi8_ZmVq0myTExOPc3StYd6i0QoLoNo',
    appId: '1:86947622453:ios:be86c55b62667617988b7c',
    messagingSenderId: '86947622453',
    projectId: 'fmfp-fbb61',
    storageBucket: 'fmfp-fbb61.appspot.com',
    iosBundleId: 'com.example.fmfp',
  );
}
